plugins {
    id 'dev.architectury.loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

group = project.maven_group
version = project.mod_version

base {
    archivesName = project.archives_name
}

repositories {
    // Add NeoForged repository.
    flatDir {
        dir 'libs'
    }
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name 'Curios maven'
        url = "https://maven.theillusivec4.top/"
    }
    maven {
        name = "BlameJared maven"
        url = uri("https://maven.blamejared.com/")
    }
    maven {
        name "KosmX's maven"
        url 'https://maven.kosmx.dev/'
    }

    maven { url 'https://www.jitpack.io' }

    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

def generatedResources = file("src/generated/resources")
def existingResources = file("src/main/resources")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    silentMojangMappingsLicense()

    runs {
        data {
            programArg "--all"
            programArgs "--mod", "netherexp"
            programArgs "--existing", existingResources.absolutePath
            programArgs "--output", generatedResources.absolutePath
            data()
        }
    }
}

dependencies {
    minecraft "net.minecraft:minecraft:$project.minecraft_version"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.21.1:2024.11.17@zip")
    }
    neoForge "net.neoforged:neoforge:$project.neoforge_version"
    modImplementation "com.github.thatjadenxgamer:elysium:${project.elysium_version}"

    modImplementation "team.lodestar.lodestone:lodestone:$project.lodestone_version"
    include "team.lodestar.lodestone:lodestone:$project.lodestone_version"

    compileOnly "top.theillusivec4.curios:curios-neoforge:$project.curios_version:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:$project.curios_version"

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-neoforge:0.5.0")))
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

// Configure Maven publishing.
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
