# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
elysium_version=5998863

## Mappings
mapping_channel=parchment
mapping_version=2023.06.26-1.20.1

## Mod Properties

mod_id=netherexp
mod_version=2.3.5
mod_name=Jaden's Nether Expansion
mod_license=CC-BY-NC-SA-4.0
mod_group_id=net.jadenxgamer.netherexp
mod_authors=ThatJadenXgamer
mod_description=A Large scale nether mod which Reimagines and Expands upon the entire Nether Dimension