# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Mod properties
mod_id = netherexp
mod_name = Jaden's Nether Expansion
mod_license = CC-BY-NC-SA-4.0
mod_version = 2.4.0
mod_group_id = net.jadenxgamer.netherexp
mod_authors = AlwaysMuddy, Shroomaniac, ceasingbonsai17, Sydokiddo, LudoCrypt, Faithful, Wawwior
mod_description = JNE is a large-scale nether mod which reimagines and expands upon every single aspect of the nether dimension!

# Minecraft properties
minecraft_version = 1.21.1
minecraft_version_range = [1.21.1]

# Parchment properties
parchment_minecraft_version = 1.21.1
parchment_mappings_version = 2024.11.17

# NeoForge properties
neoforge_version = 21.1.169
loader_version_range=[1,)

# Dependencies
lodestone_version = 1.21.1-1.7.0.268
curios_version = 9.5.1+1.21.1
elysium_version = 1.2.0-alpha.7
