# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = neoforge

# Mod properties
mod_version = 2.4.0
maven_group = net.jadenxgamer.netherexp
archives_name = netherexp

# Minecraft properties
minecraft_version = 1.21.1

# Dependencies
neoforge_version = 21.1.169
lodestone_version = 1.21.1-1.7.0.268
curios_version = 9.5.1+1.21.1
elysium_version = 1.2.0-alpha.7
yarn_mappings_patch_version = 1.21+build.4
