modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits = "AlwaysMuddy, ceasingbonsai17, Sydokiddo, LudoCrypt, Faithful, Wawwior, Alganaut, Derp_gamer22"
description='''${mod_description}'''
logoFile = "netherexp.png"

[[mixins]]
config = "${mod_id}.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "elysium_api"
type = "required"
versionRange = "[${elysium_version},)"
ordering = "NONE"
side = "BOTH"
