name: Java CI with Gradle

on:
  push:
    branches:
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    branches:
      - 'bugfix/**'
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Modify Permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: common/build/libs

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - run: chmod +x ./gradlew
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
